services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=examera
      - POSTGRES_PASSWORD=examera_pass
      - POSTGRES_DB=examera_db
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
